### ISSUE TITLE
Setting matrix for semPaths

### ISSUE THREAD

**Issue by YichiZhang2024** [sfcheung/semptools#46]
Dear Dr. Cheung and Dr. Lai,

Thanks for writing these helper functions for users in psychology. I think these functions are really easy to use and they are very helpful for customizing graphs. I tested this package on my own project and everything works out pretty well. However, I am a little confused about setting the m matrix for `semPlot` in the following lines: 
```javascript
m <- matrix(c("x1",   NA,  NA,   NA,
                NA, "x3",  NA, "x4",
              "x2",   NA,  NA,   NA), byrow = TRUE, 3, 4)
p_pa <- semPaths(fit_pa, whatLabels = "est",
           sizeMan = 10,
           edge.label.cex = 1.15,
           style = "ram",
           nCharNodes = 0, nCharEdges = 0,
           layout = m)
```
I think adding an explanation about this m matrix and how to set it would be greatly appreciated by new users like me.

**Comment by sfcheung** [comment]
Thanks, @YichiZhang2024 ! I forgot how I found out this way to set the layout. We will explain how to use this feature of semPaths (actually, of qgraph) in the next version. We may also write a function to make it easier to setup the matrix.

**Comment by sfcheung** [comment]
@YichiZhang2024 , sorry for the late reply. In the latest version (version 0.2.9.3), we added a vignette on how to use `layout_matrix`.

https://sfcheung.github.io/semptools/articles/layout_matrix.html

This is actually a feature of `semPlot::semPaths()`, and is a useful one. We added a vignette because we also make use of this feature in our functions.

A simple helper function is also added to provide an alternative way to set up the matrix:

https://sfcheung.github.io/semptools/reference/layout_matrix.html

This function can also be used for semPlot::semPaths()`.

Hope this helps.
